// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq-2Jot8l5_Pg2m86sbie_FdX28q1lhew',
    appId: '1:960255673643:web:828836e3a8f056e611316e',
    messagingSenderId: '960255673643',
    projectId: 'utkarshdeoli-d086b',
    authDomain: 'utkarshdeoli-d086b.firebaseapp.com',
    storageBucket: 'utkarshdeoli-d086b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR4lT-A2uc45ieItQqHoTUBKGN3fzPBpM',
    appId: '1:960255673643:android:d63090979c91d3db11316e',
    messagingSenderId: '960255673643',
    projectId: 'utkarshdeoli-d086b',
    storageBucket: 'utkarshdeoli-d086b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBggXeCEf6ZVi6b3lqzOT9yhNYfPiZN5uM',
    appId: '1:960255673643:ios:af22ddda1ec3fc4311316e',
    messagingSenderId: '960255673643',
    projectId: 'utkarshdeoli-d086b',
    storageBucket: 'utkarshdeoli-d086b.appspot.com',
    iosClientId: '960255673643-e09qrmlueu6gphanvvf8i4r60ush7u14.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
